### ISSUE TITLE
Markdown Support

### ISSUE THREAD

**Issue by rahul286** [benbalter/wordpress-github-sync#33]
Started using this on first live website. Really nice work. :+1: 

It will be great if there is markdown support. It may be enabled/disabled via settings.

For custom HTML in WordPress posts, we can export it as HTML only. Converting it to HTML may result is loss of HTML attributes and other info.

**Comment by mAAdhaTTah** [comment]
Could we hook into wp-markdown and use it's functionality to import/export Markdown rather than HTML? I've been using WPMD for a while and would much prefer import/export of Markdown.

**Comment by bwittorf** [comment]
For this, I changed the references in `lib/post.php` (lines 33, 94, 96) from `".html"` to `".md", so I'll have actual Markdown files exported. GitHub even displays the YAML header nice (e.g. https://github.com/bwittorf/ben.wf/blob/master/_posts/2015-01-04-im-not-a-programmer-but-towards-mastery-of-programming-as-a-skill.md). Maybe an option to set the extension which to sync with might be a solution?

**Comment by bwittorf** [comment]
Oh, and I had line 221 changed to `"post_content" => trim(html_entity_decode($body))`. Also, if I remember correctly, it's not possible to sync posts that have an <iframe> in them any longer, but I can't remember if this was .md related or an issue itself.

**Comment by benbalter** [comment]
@bwittorf are you able to submit pull requests for those changes if you think they'll benefit other users?

**Comment by bwittorf** [comment]
Sure: https://github.com/benbalter/wordpress-github-sync/pull/37
