### ISSUE TITLE
Export to GitHub times out

### ISSUE THREAD

**Issue by mAAdhaTTah** [benbalter/wordpress-github-sync#35]
I'm getting 504 Gateway errors on Nginx trying to export my whole blog to set up the plugin. Maybe we should do this in batches via AJAX?

Also, would the GitHub endpoint support us pushing multiple files in a single call, or do we have to make an individual call for each file?

Lastly, I'm not sure the post_lock set up you have works the way you think it does. If there are two separate requests exporting at the same time, each runtime environment isn't crossing into each other, so if two different people are exporting, they can do so at the same time, regardless of whether the post_lock is set. I think it needs to be persisted somewhere, like an option or transient, that's set up and deleted before each request.

I can break these into 3 different issues; the first one is the only one I'm sure needs to be addressed.

**Comment by benbalter** [comment]
> I can break these into 3 different issues; the first one is the only one I'm sure needs to be addressed.

That'd be great. 

> Also, would the GitHub endpoint support us pushing multiple files in a single call, or do we have to make an individual call for each file?

Right now we're using the CRUD API, which is one file per request. We could do a Git-clone, and work with the file system, or use some of the lower-level APIs, I believe. It's a trade off of speed for complexity as we move away from the abstractions.

> if two different people are exporting, they can do so at the same time, regardless of whether the post_lock is set. 

I'm not sure that's a big risk, but may be missing the use case.

**Comment by mAAdhaTTah** [comment]
Ok, I think trying to make wordpress play with git is more trouble than its worth. I think git would have to be installed on the server. With another plugin where I had to do something similar, I managed everything in js: get a list of ids from the server and go through them one by one.

Another option would be to export like 50 or 100 wen you click the link and defer the rest to WP_Cron. That should keep things spaced out enough so it doesn't error out.

> I'm not sure that's a big risk, but may be missing the use case.

I misunderstood its purpose, nevermind.

**Comment by mAAdhaTTah** [comment]
I'm working on the second option (using wp_cron), but I keep getting this error when continuing from the cron:

```
WordPress <--> GitHub sync error: refs/heads/master expected to be at [sha]
```

Is that sha we're looking for here tied to the post or the repo itself? If it's the repo, I think I'd cache that as an option rather than post_meta.

**Comment by benbalter** [comment]
I believe that's the blob sha, so post-specific. When you update a post, you need to specify the base sha that you're updating, which I suspect here might be stale (or just flat wrong).

**Comment by mAAdhaTTah** [comment]
It's weird because we're pushing a post for the first time, so I'm not really sure why it even has a sha to begin with... I'll have to keep investigating.

**Comment by benbalter** [comment]
> It's weird because we're pushing a post for the first time, so I'm not really sure why it even has a sha to begin with... I'll have to keep investigating.

Huh. It could be trying to update a post, when it should be creating it. IIRC they are different endpoints.

**Comment by mAAdhaTTah** [comment]
Yeah, that could be it. It looks like the same endpoint, but the create API doesn't require the sha.
