### ISSUE TITLE
Set revision author on update on the WordPress side

### ISSUE THREAD

**Issue by benbalter** [benbalter/wordpress-github-sync#4]

**Comment by mAAdhaTTah** [comment]
Does the author have to be in the WP database to be set as an author? I don't think it would make sense to add a bunch of users, but if they don't have to be, this should be pretty easy.

**Comment by benbalter** [comment]
> Does the author have to be in the WP database to be set as an author?  

I believe so.

>  I don't think it would make sense to add a bunch of users

I agree. Perhaps a default user as a fallback?

**Comment by mAAdhaTTah** [comment]
This requires the controller to be refactored into smaller Import/Export objects that can manage this properly, so bumping from 1.0.0.
