### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by drallgood** [benbalter/wordpress-github-sync#44]
```Warning: require_once(<path>/wp-content/plugins/wordpress-github-sync/vendor/autoload.php): failed to open stream: No such file or directory in <path>/wp-content/plugins/wordpress-github-sync/wordpress-github-sync.php on line 30```

**Comment by mAAdhaTTah** [comment]
If you haven't already, please install composer and run `composer install`.

**Comment by drallgood** [comment]
I did not. And that fixed it!

This should really be part of the documentation!

Thanks anyway :smile:

**Comment by mAAdhaTTah** [comment]
The plugin hasn't reached a stable, complete version yet, so no docs have been written. You can see a lot of the work being done in #42. Also, when it's deployed to .org, it won't require `composer install` anyway.
