### ISSUE TITLE
Support Importing Posts from GitHub

### ISSUE THREAD

**Issue by mAAdhaTTah** [benbalter/wordpress-github-sync#61]
We should support importing posts created on GitHub, as long as they have the basic frontmatter added, e.g. this is an importable post:

```
---
---
I wrote a post.
```

Currently, this is not possible because the controller has gotten out of control and needs to be broken down into several pieces, so this issue includes any notes about the controller refactor.

Notes:
* An Import and Export object should be split off from the controller.
* Some of the post saving can be pushed down into the Post object itself.
* We should include in the docs the default info to include in the YAML frontmatter.
* Add unit tests as we do this

**Comment by blueliquiddesigns** [comment]
Another good idea +1
