### ISSUE TITLE
PHP5.2 Support

### ISSUE THREAD

**Issue by mAAdhaTTah** [benbalter/wordpress-github-sync#62]
Besides some of the closure usage, I'm not sure what else we do much that requires PHP5.3+. We should evaluate whether we can support 5.2 and make changes to do so. If we can't, there are some 5.3 features I'd love to make use of, specifically namespaces.

**Comment by WellingGuzman** [comment]
@mAAdhaTTah we are only using closures from php 5.3, so if we change [these lines](https://github.com/benbalter/wordpress-github-sync/blob/master/lib/controller.php#L540-L542) taking out the closure, we should got php 5.2 support.

**Comment by mAAdhaTTah** [comment]
We could also use [`create_function`](http://php.net/manual/en/function.create-function.php), though that seems less than ideal. Or we could stick the function at the end of the file.

**Comment by pdclark** [comment]
@WellingGuzman That pull request should do it. I didn't have time to test, but I believe it resolves the issue you described. I just saw this passing by — if it helps, please use it. If it's not what you need, don't mind or wait for me!
