### ISSUE TITLE
Make link to post on GitHub available

### ISSUE THREAD

**Issue by mAAdhaTTah** [benbalter/wordpress-github-sync#63]
Like a "fork this post on GitHub" link.

Maybe add as a filter to `the_content`? Or a function for people to use?

**Comment by blueliquiddesigns** [comment]
Sounds like an awesome idea!

**Comment by benbalter** [comment]
If you look at the bottom of [any article on my site](http://ben.balter.com/2015/08/12/the-zen-of-github), I have an "edit this content" button. As long as you know the path you can build a link that will drop the user in an editor, and prompt them to fork/pull request when they click submit.

**Comment by mAAdhaTTah** [comment]
@benbalter Yeah, that's where I got the idea! Just need to think how I would do it in WordPress.

@blueliquiddesigns I'll take that as a vote and see about adding it soon. I'll probably do a function with instructions for adding it to the content via a filter (similar to the instructions for adding custom post types). That way, a user can add it directly in their theme if they want more control over it.

**Comment by blueliquiddesigns** [comment]
I look forward to it.
