### ISSUE TITLE
Cant find plugin

### ISSUE THREAD

**Issue by AndersWilson99** [benbalter/wordpress-github-sync#65]
I cant find a plugin named "wordpress github sync" when i search for plugins? Is it removed?

Cheers

**Comment by mAAdhaTTah** [comment]
It's not on WP.org yet, if that's what you mean. We're doing some final testing this week and plan to put it up there this weekend.

**Comment by AndersWilson99** [comment]
Aah, thats sounds very good! I have been looking for a solution to this for a long time.

**Comment by mAAdhaTTah** [comment]
[We're live.](https://wordpress.org/plugins/wp-github-sync/)
