### ISSUE TITLE
Need to change name :(

### ISSUE THREAD

**Issue by mAAdhaTTah** [benbalter/wordpress-github-sync#66]
![wordpress_ _requests_ _wordpress_plugins](https://cloud.githubusercontent.com/assets/4371429/7441631/60458e22-f0be-11e4-9d16-7206788bba68.png)

"WP-GitHub-Sync"? "Sync Posts to GitHub"? "GitHub-Post-Syncer"? Open to suggestions.

**Comment by riichiie** [comment]
WP-Github-Syncer

:)

**Comment by benbalter** [comment]
Gah. That's right. That's why it's not currently on .org. I'm not strongly opinionated here (e.g, if there's a better name than WP-GitHub-Sync), but as a data point, Google can disambiguate WP to WordPress, in term of discoverability.

**Comment by mAAdhaTTah** [comment]
[Not visible to the public yet](https://wordpress.org/plugins/wp-github-sync/).

**Comment by riichiie** [comment]
then Sync Posts to GitHub would be proper, I  think.

**Comment by mAAdhaTTah** [comment]
@riichiie Not sure what you mean? The link is the plugin I just registered, so going with wp-github-sync for the plugin's slug. We can probably continue to use [WordPress in the full name](https://wordpress.org/plugins/search.php?q=wordpress).

**Comment by riichiie** [comment]
I thought benbalter was a user....   Now I know...  ：）
waiting for the plugin

**Comment by mAAdhaTTah** [comment]
[We're live.](https://wordpress.org/plugins/wp-github-sync/)
