### ISSUE TITLE
I get an invalid HTTP request (302) error. Can't sync.

### ISSUE THREAD

**Issue by wolffe** [benbalter/wordpress-github-sync#69]
I'm using Cloudflare's flexible SSL. I have configured everything correctly inside the plugin and inside github.

**Comment by mAAdhaTTah** [comment]
A 302 is a temporary redirect. You're getting this on the initial export?

**Comment by wolffe** [comment]
Yes. The repository was created 30 minutes earlier.

**Comment by mAAdhaTTah** [comment]
Have you done a full export first? On the settings page, fill out all the info then click export to GitHub. 

And by "inside GitHub", you mean on the webhook response?

**Comment by wolffe** [comment]
Yes, I have done a full export first, I got a "successful" notification, but nothing was exported.

And yes, I mean the webhook response.

**Comment by mAAdhaTTah** [comment]
So, just to get a step-by-step view of what happened:

1. You input all the settings correctly on the settings screen (/wp-admin/options-general.php?page=wordpress-github-sync) and clicked save.
2. You clicked "Export to GitHub" on the same settings page, and when the page loaded again, it said "Export to GitHub started" (or something to that effect, I can't remember the message offhand; but it said *Started*).
3. You waited a minute or two, then went back to the settings page to see "Export to GitHub Successful".
4. You checked the webhook on GitHub and it gave you a 302. (Can you provide the full message here?)

Is this correct?

Thanks!

**Comment by wolffe** [comment]
It is correct, yes. The exact message was:

Invalid HTTP request: 302.

I have deactivated the plugin for now.

**Comment by mAAdhaTTah** [comment]
Are you using [this plugin](https://wordpress.org/plugins/cloudflare-flexible-ssl/)? This might be outside of our ability to do anything about.

**Comment by mAAdhaTTah** [comment]
Maybe check if ajax requests are handled properly by that plugin or your current setup. The weird thing is this should really affect outgoing GitHub requests, just the incoming one, so it wouldn't completely explain why you're not able to export.

**Comment by wolffe** [comment]
No, I'm using this one for HTTPS fixes - http://mvied.com/projects/wordpress-https/ - and a free Cloudflare plan.

**Comment by wolffe** [comment]
I'll try to deactivate the SSL tonight and test it again.

**Comment by mAAdhaTTah** [comment]
If you have any additional issues with this, I'll try and help you out, but this seems like a problem beyond our control, so closing for now.
