### ISSUE TITLE
Plugin fails to activate

### ISSUE THREAD

**Issue by dcmcshan** [benbalter/wordpress-github-sync#71]
Any thoughts?  Im running 4.2.2

Warning: require_once(__DIR__/composer/autoload_real.php) [function.require-once]: failed to open stream: No such file or directory in [...]/wp-content/plugins/wp-github-sync/vendor/autoload.php on line 5

Fatal error: require_once() [function.require]: Failed opening required '__DIR__/composer/autoload_real.php' (include_path='.:/usr/local/php5/lib/php') in [...]/wp-content/plugins/wp-github-sync/vendor/autoload.php on line 5

**Comment by benbalter** [comment]
How did you install the plugin?

**Comment by mAAdhaTTah** [comment]
This is definitely correct on [.org](http://plugins.svn.wordpress.org/wp-github-sync/tags/1.0.1/vendor/). Did you download the project from GitHub? If so, please run `composer install` in the plugin directory to install the dependencies. If you're still having issues, let us know.

**Comment by mAAdhaTTah** [comment]
Closing this issue for now, but @dcmcshan if you're still experiencing problems activating the plugin, feel free to reopen.
