### ISSUE TITLE
Don't export to gh private articles

### ISSUE THREAD

**Issue by Tonyz1** [benbalter/wordpress-github-sync#73]
The plugin should export to gh only public flagged wp posts

**Comment by mAAdhaTTah** [comment]
That should be the case, are you seeing different behavior?

**Comment by Tonyz1** [comment]
I wrote a wp post flagged it pwd protected but it shows publicly in gh.

**Comment by mAAdhaTTah** [comment]
My bad, I thought pw protected posts were covered by the post status. Will fix.

**Comment by mAAdhaTTah** [comment]
This is fixed in the latest version. Please update the plugin and let me know if you still have any issues.
