### ISSUE TITLE
Drafts don't save properly without a post_name

### ISSUE THREAD

**Issue by hansmosh** [benbalter/wordpress-github-sync#74]
Preface:
I enabled syncing of drafts according to the instructions
https://github.com/benbalter/wordpress-github-sync#custom-post-type--status-support

Problem:
Drafts save to github as '2015-06-26-.md' without a name. The big issue here is that if I have two drafts on the same day, they keep wiping each other out. Wordpress does not assign a post_name until published.

Workaround:
From the Posts page on wordpress, you can click "quick edit" and set a "slug". This is the post_name.

Solution:
Maybe use something besides post_name if it is empty.

**Comment by mAAdhaTTah** [comment]
Thanks for reporting! Working on this now.

**Comment by mAAdhaTTah** [comment]
This is fixed in the latest version. Please update the plugin and let me know if you still have any issues.

**Comment by hansmosh** [comment]
I haven't tried it out yet, but I glanced at the code and it looks good. Thanks!
