### ISSUE TITLE
Sync for Custom Post Type Only

### ISSUE THREAD

**Issue by kutec** [benbalter/wordpress-github-sync#75]
Hi,

I want to enable sync for only custom post type. Means I don't want to sync up regular WP posts and pages but the only specific post type.

Is it possible?

Thanks.

**Comment by mAAdhaTTah** [comment]
Yes, this is possible. Use the `wpghs_whitelisted_post_types` filter and just return the post type(s) you'd like to export. See the [README](https://github.com/benbalter/wordpress-github-sync/blob/master/README.md#custom-post-type--status-support) for how to add those post type(s) to the default `post` type.
