### ISSUE TITLE
does this support github oauth2?

### ISSUE THREAD

**Issue by lzufalcon** [benbalter/wordpress-github-sync#77]
Hello, @benbalter 

Seems github's **Personal access tokens** doesn't support `public_repo` scope now, so, will our project support oauth2 (with client id and secret) in the future?

Here is the php-oauth2 support I have found: 

* https://developer.github.com/v3/oauth/
* https://github.com/adoy/PHP-OAuth2/
* https://github.com/mahfuz05/oauth2-client

hope it helps.

Thanks,

**Comment by mAAdhaTTah** [comment]
They don't? https://www.evernote.com/l/AFmvZEwDziRFsLTgPvP-nEwoAtEY5qJ09lI

Do you have a link that confirms this?

**Comment by lzufalcon** [comment]
Just tried again, the `public_repo` is enabled by default before create, but after generate one token and reenter into it via the *Edit* button and the `public_repo` is not enabled...

**Comment by lzufalcon** [comment]
I'm sorry, Just found this prompt:

> Some of the scopes you’ve selected are included in other scopes. Only the minimum set of necessary scopes has been saved.

And tried to disable the other three, and only reserve `public_repo`, now, it is there, will try the powerful plugin again.

Thanks very much!

**Comment by mAAdhaTTah** [comment]
:+1:

**Comment by lzufalcon** [comment]
hello, @mAAdhaTTah 

Even with the `public_repo` scope enabled, this plugin still not work with my 3.3.1 WordPress (Can not upgrade the WP itself easily for I have installed lots of the other plugins), both export and import failed.

1. Export, simply print "Export to Github Started..." and no more actions after even 30 minutes.
2. Pushed something to github repo, and simply return 500 error:

```
Headers
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection: keep-alive
Content-Type: text/html; charset=UTF-8
Date: Sat, 15 Aug 2015 15:19:28 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Server: nginx
Set-Cookie: qtrans_cookie_test=qTranslate+Cookie+Test; path=/; domain=www.tinylab.org, PHPSESSID=buddkr94sp62kkiqjmhhk97tq4; path=/
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: PHP/5.3.10-1ubuntu3.13
Body
```

Is anybody test this plugin with 3.3.1 WP?

Thanks & BR,

**Comment by mAAdhaTTah** [comment]
First place to look would be your logs; let me know if/what errors you see there.

However, 3.3.1 is so old, I can't guarantee it'll work on that version. I _highly_ recommend taking the time to upgrade, as there have been a **huge** number of enhancements for WordPress in the time between then and now, and it's extremely likely your website has exposed security holes you don't know about because it's running such an old version. Same thing with the plugins.

**Comment by lzufalcon** [comment]
Ok, will try to upgrade the WP at first, thanks.
