### ISSUE TITLE
Markdown Code blocks Encoding Issue

### ISSUE THREAD

**Issue by blueliquiddesigns** [benbalter/wordpress-github-sync#96]
Hey guys,

Has anyone had any encoding trouble for code blocks when syncing from WordPress to GitHub?

I've got JP Markdown installed and have the following in WordPress:

	## Heading 2

	This is awesome

	> My Quote rules

	```
	<html>
	   <body>Tag</body>
	</html>

	<?php 

	echo 'print'; exit;
	```

However, when the sync is done the results in the code block are encoded:

```
&lt;html&gt;
   &lt;body&gt;Tag&lt;/body&gt;
&lt;/html&gt;

&lt;?php 

echo &#039;print&#039;; exit;
```

I haven't tested what happens when GitHub is pushed to WordPress (I'm on a local development site at the moment).

**Comment by mAAdhaTTah** [comment]
If you can do me a favor and check whether they're encoded in your database (it's the `post_content_filtered` column we're looking for), that would help. I don't think we're doing anything with it on the export side besides pulling it straight out of the database, so my first suspicion is WPMarkdown converts it on saving/retrieving.

If that's the case, you can hook in [here](https://github.com/benbalter/wordpress-github-sync/blob/master/lib/post.php#L173) to convert it back, or see if there's a setting/filter within JP Markdown to disable that.

I'm not sure how I feel about including that conversion by default, though, as I'm not entirely sure what the side effects might be.

**Comment by blueliquiddesigns** [comment]
Thanks for steering my in the right direction, @mAAdhaTTah.

The DB copy is indeed encoded. I looked closer at the Jetpack Markdown code and found that during editing the markdown is run through a code block and line block quote restoration process. This gets run right before WP places the markdown in the post editor.

The code I used to resolve the problem is as follows:

```
/* Add filter to correctly unencode our code blocks and blockquotes */
add_filter( 'wpghs_content_export', function( $content ) {

	if( class_exists( 'WPCom_Markdown' ) ) {
		$markdown = WPCom_Markdown::get_instance(); /* get the markdown instance */
		$content  = $markdown->get_parser()->codeblock_restore( $content ); /* unencode codeblocks */
		$content  = preg_replace( '/^&gt; /m', '> ', $content );/* restore beginning of line blockquotes */
	}

	return $content;
} );
```

**Comment by mAAdhaTTah** [comment]
Thanks for this. I wonder why JP Markdown converts them at all; I would have assumed that the content going into the `post_content_filtered` field was the raw Markdown.

**Comment by blueliquiddesigns** [comment]
JP Markdown is just a port of the JetPack version, but I would suggest it enhances security - i.e you don't have a security issue by outputting the raw `post_content_filtered` markdown to the browser.
