### ISSUE TITLE
Anything to be altered on WordPress site?

### ISSUE THREAD

**Issue by rpicn** [benbalter/wordpress-github-sync#97]
Hi, I have generated a personal oauth token, configured GitHub repo, secret, oauth token on WordPress site, created webHook and service, but I still can not import anything from GitHub? I guess from WordPress to GitHub is OK, because I can see a new folder generated on GitHub side. Is there anything more I should do so that I can import posts from GitHub? Thanks!

**Comment by mAAdhaTTah** [comment]
You just need to create a post with the YAML frontmatter on the top of the document and commit it to the repo. See [the README](https://github.com/benbalter/wordpress-github-sync#importing-from-github) for a full explanation.

If you have any other questions/issues or the README is unclear, feel free to reopen this ticket.

**Comment by rpicn** [comment]
Oops, I jumped that gun... sorry and thanks!
