### ISSUE TITLE
PHP Notice: Undefined property: WP_Error::$tree in /plugins/wp-github-sync/lib/api.php on line 46

### ISSUE THREAD

**Issue by blueliquiddesigns** [benbalter/wordpress-github-sync#99]
When saving a post set up to be synced with GitHub the following error displays sometimes:

`PHP Notice: Undefined property: WP_Error::$tree in /plugins/wp-github-sync/lib/api.php on line 46`

**Comment by blueliquiddesigns** [comment]
Full Stack Trace here: https://gist.github.com/blueliquiddesigns/dacc32880a1c2317321e

**Comment by mAAdhaTTah** [comment]
Thanks; I think this and the other issue you open are related. I was missing a check for `is_wp_error` after the API call. Which is why you see the invalid property bug in the other issue you opened.

Thanks, this should be a quick fix.

**Comment by mAAdhaTTah** [comment]
BTW, thanks so much for the stack trace; made things much easier!

**Comment by blueliquiddesigns** [comment]
Not a problem. Nice work on fixing the bugs so quickly.
